# Grundkonfiguration fuer manage-terraform.py
ROOT_DIR="/mnt/terraform/terraform-infrastructure"
TEMPLATE_DIR="/mnt/terraform/terraform-infrastructure/template"
ENVIRONMENTS_DIR="/mnt/terraform/terraform-infrastructure/environments"
MASTER_BRANCH="master"
DEVELOP_BRANCH="develop"
GIT_REMOTE_NAME="origin"
GIT_GROUP_URL="https://gitlab.team-netz.net/team-netz"
GIT_REMOTE_URL=""
GIT_USERNAME=""
GIT_PASSWORD=""
GIT_ACCESS_TOKEN="glpat-K-MICmMWALpv7d3zNEHG9G86MQp1OjEH.01.0w082o6yq"
GIT_CREATE_REMOTE_PROJECTS="true"
GITLAB_API_URL="https://gitlab.team-netz.net/api/v4"
GIT_COMMIT_AUTHOR_NAME="Terraform Manager"
GIT_COMMIT_AUTHOR_EMAIL="terraform-manager@example.local"
GIT_TEST_PROJECT_PREFIX="terraform-manager-test"
ACTIVE_ENVIRONMENT="arz"
TERRAFORM_TARGET_BRANCH="develop"
